[package]
name = "bigdrill"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", default-features = true, features = ["bevy_gltf", "debug", "bevy_ui_widgets", "dynamic_linking", "serialize", "picking", "common_api"] }
bevy_ecs = "0.19"
bevy-trait-query = "0.19.0"
bevy_diesel = "0.2.0"
moonshine-view = "0.4.0"
moonshine-kind = "0.5.0"
bevy_replicon = {version = "0.42.1", features = ["client", "server"]}
bevy_renet = "5.0.0"
bevy_replicon_renet = "0.18"
bevy_tween = {version = "0.13.0", features = ["bevy_asset"]}
bevy_tweening = "0.16.0"
bevy_dylib = { version = "0.19.0" }
inventory = "0.3.24"
rand = "0.10"
bevy_rand = "0.15.1"
bevy_prng = { version = "0.15", features = ["wyrand"] }
wyrand = {version = "0.4.1", features=["rand_core"]}
serde = "1.0.228"
bevy_immediate = "0.8.0"
bevy_flair = "0.8.0"
bevy_mod_opacity = "0.6.0"


# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
debug = false
incremental = true
lto = "off"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
